[package]
name = "crates-io-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
crates_io_api = "0.11.0"
log = "0.4.21"
simple-log = "1.6.0"
chrono = "0.4.38"
anyhow = "1.0.83"
reqwest = "0.12.4"
ratelimit = "0.9.1"
serde_json = "1.0.117"